---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: tagower-test-flask-deployment
   labels:
     username: tagower
     env: test
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: tagower-test-flask
   template:
     metadata:
       labels:
         app: tagower-test-flask
         username: tagower
         env: test
     spec:
       containers:
         - name: tagower-flask
           image: tagower/gene_api:hw07
           env:
           - name: REDIS_HOST
             value: "gene_apihw07.py"
           volumeMounts:
           - name: tagower-test-data
             mountPath: "/data"
       volumes:
       - name: tagower-test-data
         persistentVolumeClaim:
           claimName: tagower-test-data
