---
apiVersion: v1
kind: Service
metadata:
  name: tagower-test-flask-service
spec:
  type: ClusterIP
  selector:
    app: tagower-test-flask
    username: tagower
    env: test
  ports:
  - name: tagower-flask-port
    port: 5000
    targetPort: 5000
